---
- name: create ca-csr.json
  ansible.builtin.template:
    src: ca-csr.json.j2
    dest: "{{ CERTS_LOCATION }}/ca-csr.json"

- name: create CA key and cert
  ansible.builtin.shell:
    chdir: "{{ CERTS_LOCATION }}"
    cmd: cfssl gencert -initca ca-csr.json | cfssljson -bare ca –
    creates: 
      - "{{ CERTS_LOCATION }}/ca-key.pem"
      - "{{ CERTS_LOCATION }}/ca.pem"

- name: create ca-config.json
  ansible.builtin.template:
    src: ca-config.json.j2
    dest: "{{ CERTS_LOCATION }}/ca-config.json"